let ativo1 = document.querySelector('.ativo-1')
let ativo2 = document.querySelector('.ativo-2')
let ativo3 = document.querySelector('.ativo-3')
let ativo4 = document.querySelector('.ativo-4')

let show0 = document.querySelector('.show0')
let show1 = document.querySelector('.show1')
let show2 = document.querySelector('.show2')
let show3 = document.querySelector('.show3')
let show4 = document.querySelector('.show4')

ativo1.addEventListener('click', function(){
        ativo1.classList.add('show1')
        ativo1.classList.remove('show0')
        ativo1.classList.remove('show1')
        ativo1.classList.remove('show4')
        ativo1.classList.remove('show3')
})
ativo2.addEventListener('click', function(){
    show2.classList.add('show2')
    show2.classList.remove('show0')
    show2.classList.remove('show1')
    show2.classList.remove('show4')
    show2.classList.remove('show3')
})
ativo3.addEventListener('click', function(){
    show3.classList.add('show3')
    show3.classList.remove('show0')
    show3.classList.remove('show1')
    show3.classList.remove('show4')
    show3.classList.remove('show2')
})
ativo4.addEventListener('click', function(){
    show4.classList.add('show4')
    show4.classList.remove('show0')
    show4.classList.remove('show1')
    show4.classList.remove('show2')
    show4.classList.remove('show3')

})